### ISSUE TITLE
Using the latest firmware the ecowitt gatewal and this addon we get the ff error

### ISSUE THREAD

**Issue by fuzails** [garbled1/homeassistant_ecowitt#111]
2022-05-03 11:48:39 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 334, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.InvalidURLError: 400, message='Unexpected char in url schema'

Also dont see any sensors being reported, GW1000B_V1.7.2 is the gateway firmware

**Comment by fuzails** [comment]
narrowwed this down to the instructions saying that path doesnt matter as long as it ends with / but adding any value besides / results in this error e.g. ew/
