### ISSUE TITLE
Entity not discovered by home assistant

### ISSUE THREAD

**Issue by cdouet** [garbled1/homeassistant_ecowitt#12]
Hello,

I have managed to install the ecowitt integration on home assistant (no error message). However, I cant find any related entity.

I wonder if my ecowitt is uploading anything on my home assistant Rpi4 as I cannot input any username/password in the WS View app. 

Can you please tell me if I have missed something here?

Thanks in advance,

Charles

**Comment by MimbaMonkeyHouse** [comment]
How did you solve this issue? I have the same problem...
Logs:
```
2020-09-13 22:50:09 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.8/site-packages/pyecowitt/ecowitt.py", line 262, in handler
    weather_data = self.convert_units(data_copy)
  File "/usr/local/lib/python3.8/site-packages/pyecowitt/ecowitt.py", line 163, in convert_units
    data["windspdkmh_avg10m"] = float(data["windspdmph_avg10m"]
TypeError: float expected at most 1 argument, got 2
2020-09-13 22:50:11 WARNING (MainThread) [custom_components.ecowitt] Unhandled sensor type maxdailygustms value 1.0, file a PR.
```
