### ISSUE TITLE
Installation do not work

### ISSUE THREAD

**Issue by sns5400** [garbled1/homeassistant_ecowitt#160]
i try to install Ecowitt and follow your installation text.
In HACS integration view no "options"  menu on card.
In integration and devices search for ecowitt error "config flow cold not be loaded, invalid handler specified.
In log:

Error occurred loading flow for integration ecowitt: cannot import name 'async_get_registry' from 'homeassistant.helpers.entity_registry' (/usr/src/homeassistant/homeassistant/helpers/entity_registry.py)

Any idee how to fix this?

**Comment by stiltjack** [comment]
Same problem here.

`Logger: homeassistant.config_entries
Source: config_entries.py:865
First occurred: 13:26:04 (2 occurrences)
Last logged: 13:26:16

Error occurred loading flow for integration ecowitt: cannot import name 'async_get_registry' from 'homeassistant.helpers.entity_registry' (/usr/src/homeassistant/homeassistant/helpers/entity_registry.py)`

I had the Ecowitt Weather Station integration running successfully until yesterday - foolishly removed it to try the "official" integration. I get the same error for that as well.

Home Assistant 2023.8.2
Supervisor 2023.08.1
Operating System 10.4
Frontend 20230802.0 - latest

Edit: Sorry, I see this is a duplicate.

**Comment by stiltjack** [comment]
Found the solution:

Using HA file editor, go to “/config/custom_components/ecowitt/”
Edit line 21 to " async_get as async_get_entity_registry,"
Save file.

Thanks to @mortenx in HA Forum.

**Comment by sns5400** [comment]
Fine to here you found a solution but wich file you edit, there are:
__init__.py; binary_sensor.py; config_flow.py; const.py; manifest.json;
sechema.py; sensor.py; translation.py

Thank you in advance

**Comment by stiltjack** [comment]
Sorry.

`__init__.py`

**Comment by sns5400** [comment]
Thanks for info but still not complete.
In the configuration text there is:

Ecowitt should now appear as a card under the HA Integrations page
with "Options" selection available at the bottom of the card.

Have you the options menu ?

**Comment by stiltjack** [comment]
Cards on the integrations page changed a couple of months ago. The latest looks like this:
![image](https://github.com/garbled1/homeassistant_ecowitt/assets/67193733/c145022f-0ac2-4655-a487-9ec250da4cab)
To get the options menu, click on **>** then on **configure**.

**Comment by sns5400** [comment]
its fixid thank to your input, i check again my phone app and protocol whas
not ecowitt afther changing to ecowitt everything ok
[image: working 2023-08-15_9-23-24.png]

**Comment by jiclausen** [comment]
i am getting this error

Logger: homeassistant.config_entries
Source: config_entries.py:402
First occurred: 22.33.52 (5 occurrences)
Last logged: 22.38.24

Error setting up entry Ecowitt for ecowitt
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 402, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ecowitt/__init__.py", line 155, in async_setup_entry
    ws = EcoWittListener(port=entry.data[CONF_PORT])
                              ~~~~~~~~~~^^^^^^^^^^^
KeyError: 'port'
