### ISSUE TITLE
TypeError: an integer is required (got type str)

### ISSUE THREAD

**Issue by freman** [garbled1/homeassistant_ecowitt#40]
I'm assuming this is coming from ecowitt because it's mentioned in the stack.

Standard install, got it working today so latest version.

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 283, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 320, in _async_write_ha_state
    sstate = self.state
  File "/config/custom_components/ecowitt/sensor.py", line 54, in state
    dt_util.utc_from_timestamp(self._ws.last_values[self._key])
  File "/usr/src/homeassistant/homeassistant/util/dt.py", line 100, in utc_from_timestamp
    return UTC.localize(dt.datetime.utcfromtimestamp(timestamp))
TypeError: an integer is required (got type str)
```

**Comment by garbled1** [comment]
It looks like your lightning sensor is reporting something other than an integer for the timestamp..

If you feel like debugging it.. edit /config/custom_components/ecowitt/sensor.py and at line 53 insert a line at the same indent as the return statement:
_LOGGER.warning("timestamp=%s", self._ws.last_values[self._key])

Maybe yours reports the time differently than others?

**Comment by freman** [comment]
Sorry it took so long to do this, life got in the road. would byou belive timestapm is empty?

```
2021-02-16 11:55:16 WARNING (MainThread) [custom_components.ecowitt.sensor] timestamp=
2021-02-16 11:55:16 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 283, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 320, in _async_write_ha_state
    sstate = self.state
  File "/config/custom_components/ecowitt/sensor.py", line 55, in state
    dt_util.utc_from_timestamp(self._ws.last_values[self._key])
  File "/usr/src/homeassistant/homeassistant/util/dt.py", line 100, in utc_from_timestamp
    return UTC.localize(dt.datetime.utcfromtimestamp(timestamp))
TypeError: an integer is required (got type str)
```

**Comment by garbled1** [comment]
Huh.  Who knew it would report like that then...   I'll try to fix this this weekend.. but I think the fix is as easy as throwing an if in there to check if the value is == '' and if it is returning STATE_UNKNOWN...

Crazy that they just send an empty timestamp for it.  I don't actually own one yet, so only had other people's data to work with.

**Comment by garbled1** [comment]
Could you replace your sensor.py with the one I just committed?  If it works I'll publish new.

**Comment by freman** [comment]
I'm afraid I can't test any more, we've had several hundred lightning strikes in the past couple of days and it's working fine now

2021-02-24 22:02:45 WARNING (MainThread) [custom_components.ecowitt.sensor] timestamp=1614137572


:D

**Comment by garbled1** [comment]
The joys of testing code that is dependent upon the actual environment...

**Comment by sam-ward** [comment]
I came across the same problem/errors with my HA instance and the ecowitt integration. 

I have updated my sensor.py with the 2 extra lines as per your commit, and now the last lightning strike sensor/entity is reporting "unknown" (I havent had lightning for a while).  Hopefully we will get a storm through in the next week or so and i'll be able to confirm whether it still works as expected when there is lightning around.

**Comment by sam-ward** [comment]
Finally had a storm come through close enough that we were able to register lightning. And I can confirm that the lightning sensor is now reporting the last lightning strike as "1 day ago" (vs the "unknown" it was showing previously.

So for a sample of n=1, the change to the code works for me.
