### ISSUE TITLE
Gateway WH2650A no data

### ISSUE THREAD

**Issue by gio82c** [garbled1/homeassistant_ecowitt#42]
Hi barbled1, i have one GW-1000 and work goods, now i have install another gateway but I don't get any data..

Can you help me?

![20210226_142016](https://user-images.githubusercontent.com/61468260/109305664-5b4cd700-783e-11eb-900b-b3034ed7836d.jpg)

**Comment by gio82c** [comment]
Error unloading entry Ecowitt on port 4199 for ecowitt
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 325, in async_unload
    result = await component.async_unload_entry(hass, self)  # type: ignore
  File "/config/custom_components/ecowitt/__init__.py", line 290, in async_unload_entry
    await ws.stop()
  File "/usr/local/lib/python3.8/site-packages/pyecowitt/ecowitt.py", line 304, in stop
    await self.site.stop()
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_runner.py", line 68, in stop
    self._runner._check_site(self)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_runner.py", line 319, in _check_site
    raise RuntimeError(f"Site {site} is not registered in runner {self}")
RuntimeError: Site <aiohttp.web_runner.TCPSite object at 0x7f8752bba0> is not registered in runner <aiohttp.web_runner.ServerRunner object at 0x7f874d4d10>

**Comment by garbled1** [comment]
Hrmm.. are you trying to run two ecowitt listeners?  I haven't actually tried this..  Are they configured on different ports?  If they are both sending to port 4199, that wouldn't work..

**Comment by gio82c** [comment]
yes there are 2 ports

**Comment by gio82c** [comment]
i also try to remove the gw-1000 and try with only the new one, but nothing..

**Comment by gio82c** [comment]
Last logged: 15:59:14

Error unloading entry Ecowitt on port 4199 for sensor
Error unloading entry Ecowitt on port 4199 for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 325, in async_unload
    result = await component.async_unload_entry(hass, self)  # type: ignore
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 72, in async_unload_entry
    return await hass.data[DOMAIN].async_unload_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 172, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!

**Comment by cesarpuig** [comment]
Hello, same device, same error, have you managed to fix it?

`Logger: homeassistant.config_entries
Source: helpers/entity_component.py:177
First occurred: 16:29:00 (2 occurrences)
Last logged: 16:29:00

Error unloading entry Ecowitt on port 4199 for sensor
Error unloading entry Ecowitt on port 4199 for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 452, in async_unload
    result = await component.async_unload_entry(hass, self)  # type: ignore
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 210, in async_unload_entry
    return await component.async_unload_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 177, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!`

Thank you

**Comment by cesarpuig** [comment]
Sorry, it works perfectly, I was not entering the ip correctly because I was including http:// before the IP address.

I have used WS View Plus to configure my device (WH2650-WIFI0515)

My device is the same as the photo of the #gio82c the waldbeck halley, version 1.6.8.

#garbled1, thank you very much for your great work

**Comment by sidwin9** [comment]
Hello, help me
I have correctly entered my local IP address of my HASS server, the communication port 4199 which is not used on my router, I have correctly configured Ecowitt in integration but HASS does not detect anything
