### ISSUE TITLE
home assistant freezing on startup

### ISSUE THREAD

**Issue by terrorforma** [garbled1/homeassistant_ecowitt#5]
Hey. I'm currently running home assistant 0.110.3, with the addon added through HACS.

I'm attempting to get this working. Have set up everything as per your instructions, with port 4199 in the WS View app.... 

![Screenshot_20200530-221628](https://user-images.githubusercontent.com/35564429/83328631-87452700-a2c3-11ea-8431-3ef53a15b01b.jpg)

And the following code in my configuration.yaml file

ecowitt:
  port: 4199
  barounit: metric
  windunit: metric
  rainunit: metric
  windchillunit: hybrid

But on startup, Home assistant crashes, and the error in the log, repeated over and over again is:

2020-05-30 22:20:04 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 275, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp\_http_parser.pyx", line 523, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.InvalidURLError: 400, message='invalid URL'

The only other ecowitt related logs are the standard...
2020-05-30 22:01:28 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for ecowitt which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-05-30 22:01:46 INFO (MainThread) [homeassistant.setup] Setting up ecowitt
2020-05-30 22:01:59 WARNING (MainThread) [homeassistant.setup] Setup of ecowitt is taking over 10 seconds.

I'm not sure what else to try. If I comment our the ecowitt section of the confiuration.yaml file, all works well. If I try browsing to http://192.168.0.35:4199/, I get "OK" so I'm guessing that side is working?

Thanks

**Comment by terrorforma** [comment]
OK I've solved it. It turns out that the path needs to be "/". I didn't change this so I thought your instructions of "leave as default" meant leave it blank. Perhaps a change in your documentation is required to make sure "/" is entered?

Thanks!

**Comment by garbled1** [comment]
Hrmm.. looking at your config vs mine, the only thing different was I left the /data/report string in "Path:".  I wouldn't think that mattered, but maybe you need something there, like even a / ?  Ha, you just found that.
