### ISSUE TITLE
Invalid URL error

### ISSUE THREAD

**Issue by penright** [garbled1/homeassistant_ecowitt#66]
Just tried to install it on HA 2021.7
Looks like there is a conflict with nabucasa and just one of my google nest. Not sure why the other one is not showing up.
I only get the nabucasa errors when I have the integration turned on. I am including a screenshot of Wireshark showing the conversation.  I am assuming the URL is invalid because of the error thrown.
Also, notice my GW-1000 version is 1.6.8 
Did they change something on you?

```
2021-07-13 15:51:05 INFO (MainThread) [hass_nabucasa.google_report_state] Connected
2021-07-13 15:51:24 WARNING (Thread-7) [pychromecast.socket_client] [Kitchen speaker(192.168.1.184):8009] Heartbeat timeout, resetting connection
2021-07-13 15:51:24 INFO (Thread-7) [pychromecast.controllers] Receiver:channel_disconnected
2021-07-13 15:51:54 ERROR (Thread-7) [pychromecast.socket_client] [Kitchen speaker(192.168.1.184):8009] Failed to connect to service ServiceInfo(type='host', data=('192.168.1.184', 8009)), retrying in 5.0s
2021-07-13 15:51:54 INFO (Thread-7) [pychromecast.socket_client] [Kitchen speaker(192.168.1.184):8009] Connection reestablished!
2021-07-13 15:52:38 INFO (SyncWorker_1) [homeassistant.loader] Loaded ssdp from homeassistant.components.ssdp
2021-07-13 15:52:48 WARNING (Thread-7) [pychromecast.socket_client] [Kitchen speaker(192.168.1.184):8009] Heartbeat timeout, resetting connection
2021-07-13 15:52:48 INFO (Thread-7) [pychromecast.controllers] Receiver:channel_disconnected
2021-07-13 15:53:18 ERROR (Thread-7) [pychromecast.socket_client] [Kitchen speaker(192.168.1.184):8009] Failed to connect to service ServiceInfo(type='host', data=('192.168.1.184', 8009)), retrying in 5.0s
2021-07-13 15:54:14 INFO (Thread-7) [pychromecast.socket_client] [Kitchen speaker(192.168.1.184):8009] Connection reestablished!
2021-07-13 15:54:44 WARNING (Thread-7) [pychromecast.socket_client] [Kitchen speaker(192.168.1.184):8009] Heartbeat timeout, resetting connection
2021-07-13 15:54:44 INFO (Thread-7) [pychromecast.controllers] Receiver:channel_disconnected
2021-07-13 15:54:59 INFO (Thread-7) [pychromecast.socket_client] [Kitchen speaker(192.168.1.184):8009] Connection reestablished!
2021-07-13 15:55:31 INFO (MainThread) [homeassistant.setup] Setting up ecowitt
2021-07-13 15:55:31 INFO (MainThread) [homeassistant.setup] Setup of domain ecowitt took 0.0 seconds
2021-07-13 15:55:48 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 314, in data_received
messages, upgraded, tail = self._request_parser.feed_data(data)
File "aiohttp/_http_parser.pyx", line 546, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.InvalidURLError: 400, message='invalid URL'

```

![image](https://user-images.githubusercontent.com/21042538/125526189-b9b60307-c69d-40be-a041-365ffd2d6375.png)

**Comment by penright** [comment]
Does anyone have a sword I can borrow?
It was the '/' in the path. Sorry for the confusion.
