### ISSUE TITLE
Warning flagged in 2021.12

### ISSUE THREAD

**Issue by sam-ward** [garbled1/homeassistant_ecowitt#87]
I have just upgraded to 2021.12.1, and the following message is being recorded in the HA log file:

sensor.ecowitt_last_lightning_strike is providing a string for its state, while the device class is 'timestamp', this is not valid and will be unsupported from Home Assistant 2022.2. Please report it to the custom component author.

Cheers
Sam

**Comment by garbled1** [comment]
Hrmm, I'll have to fix this.   I'm hoping to have ecowitt moved to base HA by then, and I think this is already fixed in my PR to do that, so, maybe it will be a non-issue.

I'll wait on this for now, and hopefully not have to fix it separately here.

**Comment by jwelvaert** [comment]
> Hrmm, I'll have to fix this. I'm hoping to have ecowitt moved to base HA by then, and I think this is already fixed in my PR to do that, so, maybe it will be a non-issue.
> 
> I'll wait on this for now, and hopefully not have to fix it separately here.

Can you give us an update on this? Been getting this error since 2022.3.

```
Logger: homeassistant
Source: components/sensor/__init__.py:392
First occurred: March 9, 2022, 6:47:28 PM (490 occurrences)
Last logged: 3:04:36 AM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 381, in state
    if value.tzinfo is None:
AttributeError: 'str' object has no attribute 'tzinfo'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 540, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 590, in _async_write_ha_state
    state = self._stringify_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 559, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 392, in state
    raise ValueError(
ValueError: Invalid datetime: sensor.last_lightning_strike has a timestamp device class but does not provide a datetime state but <class 'str'>
```

**Comment by sam-ward** [comment]
> > Hrmm, I'll have to fix this. I'm hoping to have ecowitt moved to base HA by then, and I think this is already fixed in my PR to do that, so, maybe it will be a non-issue.
> > I'll wait on this for now, and hopefully not have to fix it separately here.
> 
> Can you give us an update on this? Been getting this error since 2022.3.
 
I have just opened PR #100 with a fix to this issue.  If you want to do it manually, you need to edit the sensor.py and remove the ".isoformat()" from the end of line 59 (leave the closing ')' there though)

**Comment by sam-ward** [comment]
I've been doing some more testing, and the error is being thrown when the last_lightning_strike timestamp is unknown.  So reasons I dont understand, when the ecowitt device has a null/unknown timestamp, the line https://github.com/garbled1/homeassistant_ecowitt/blob/3ad3e0373bae780a8de4787572d74613d3d5f566/custom_components/ecowitt/sensor.py#L56 where its returning STATE_UNKNOWN is not being handled as I would expect by the HA core.

I have also manually tested the PR to integrate Ecowitt into HA Core, but it still seems to be throwing an error in the same codepath.
```TypeError: an integer is required (got type str)```

**Comment by sam-ward** [comment]
@garbled1 I have been doing some more testing with the PR that you submitted to HA Core, and I think I may have gotten to the bottom of it.  I think the Ecowitt devices are always sending a value for the last_lightning_strike timestamp, but its sending a null/empty string value, which is whats generating the error with the utc_from_timestamp.  What I did in my local copy was to add another data check to catch this scenario, and importantly for it to return None. This seems to allow HA to process the value and report it as "Unknown" in the UI.  For some reason if you return STATE_UNKNOWN then you still get a stack trace in the logs, where as returning None seems to work as you would expect it to.

```class EcowittLightningTimeSensor(EcowittSensor):
    """Represent an Ecowitt lightning last strike time sensor."""

    @property
    def native_value(self):
        """Return the state of the sensor."""
        if self._key not in self.data.client.last_values:
            _LOGGER.warning(
                "Sensor %s not in last update, check range or battery", self._key
            )
            return STATE_UNKNOWN
        if self.device.get_value() == "" or self.device.get_value() is None:
            #No last timestamp available.
            return None
        # strikes are reported in UTC
        return dt_util.as_local(dt_util.utc_from_timestamp(self.device.get_value()))
```

I think it relates to the comment:

```Timestamp. Requires native_value to return a Python datetime.datetime object, with time zone information, or None.``` 

in the [Sensor Entity Available Device Class documentation](https://developers.home-assistant.io/docs/core/entity/sensor#available-device-classes) for the timestamp class.

**Comment by ocso** [comment]
@sam-ward or you just return None instead of STATE_UNKNOWN in sensor.py:

```
    @property
    def native_value(self):
        """Return the state of the sensor."""
        if self._key in self._ws.last_values:
            # The lightning time is reported in UTC, hooray.
            if self._dc == DEVICE_CLASS_TIMESTAMP:
                if not isinstance(self._ws.last_values[self._key], int):
                    return None
```
